@echo off
::define your phase 'production or testing'
set phase=production
set build_dir=build-result

echo ============== Start building ==============
echo [Make sure you have installed Sencha Cmd!]

::create 'build' directory
if exist %build_dir% rmdir /Q /S %build_dir%
mkdir %build_dir%

::cd to sencha toucha app directory and build it
::make sure you have installed sencha cmd (http://www.sencha.com/products/sencha-cmd/download)
cd static
sencha app build %phase%

::directories 'archive' and 'build' will be generated by sencha build
::copy sencha touch files to build/static
move build/Trister/%phase% ../%build_dir%/static

::delete the two generated directories
rmdir /Q /S archive
rmdir /Q /S  build

::copy favicon.ico to build
copy favicon.ico ..\%build_dir%\static\

::copy flask files to build
cd ..
copy *.py %build_dir%\
copy requirements.txt %build_dir%\

echo ============== Building successfully ==============
echo All files in [%build_dir%] directory are ready to be pulibshed!
