#!/bin/bash

# define your phase 'production or testing'
phase="production"
build_dir="build-result"

echo "============== Start building =============="
echo "[Make sure you have installed Sencha Cmd!]"

# create 'build' directory
rm -rf $build_dir/
mkdir $build_dir

# cd to sencha toucha app directory and build it
# make sure you have installed sencha cmd (http://www.sencha.com/products/sencha-cmd/download)
cd static
sencha app build $phase

# directories 'archive' and 'build' will be generated by sencha build
# copy sencha touch files to build/static
mv build/Trister/$phase ../$build_dir/static
# delete the two generated directories
rm -rf archive/
rm -rf build/

# copy favicon.ico to build
cp favicon.ico ../$build_dir/static/

# copy flask files to build
cd ..
cp *.py requirements.txt $build_dir/

echo "============== Building successfully =============="
echo 'All files in ['$build_dir'] directory are ready to be pulibshed!'
