#!/bin/bash

# define your phase 'production or testing'
phase="testing"

echo "============== Start building =============="
echo "[Make sure you have installed Sencha Cmd!]"

# create 'build' directory
rm -rf build/
mkdir build

# cd to sencha toucha app directory and build it
# make sure you have installed sencha cmd (http://www.sencha.com/products/sencha-cmd/download)
cd static
sencha app build $phase

# directories 'archive' and 'build' will be generated by sencha build
# copy sencha touch files to build/static
mv build/Trister/$phase ../build/static
# delete the two generated directories
rm -rf archive/
rm -rf build/

# copy favicon.ico to build
cp favicon.ico ../build/static/

# copy flask files to build
cd ..
cp *.py requirements.txt build/

echo "============== Building successfully =============="
echo 'All files in [build] directory are ready to be pulibshed!'